### ISSUE TITLE
no Refresh token?

### ISSUE THREAD

**Issue by uknowmeright** [iainmullan/spotify-token-swap-php#1]
Great repository! Am using it now. Would it be possible to implement the refresh token swap as well?

**Comment by joebenton** [comment]
I have updated this script to include the refresh token swap and changed the Spotify API url. Pull request here:
https://github.com/iainmullan/spotify-token-swap-php/pull/2

Or you can also find it here: (https://github.com/joebenton/spotify-token-swap-php)
